version: "3.9"

services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  fastapi:
    restart: on-failure
    container_name: fastapi
    build: .
    working_dir: /usr/src/api
    entrypoint: ./scripts/entrypoint.sh
    volumes:
      - .:/usr/src/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres:postgres

volumes:
  postgres-data:
    driver: local