[tool.poetry]
name = "roadmap-project"
version = "0.1.0"
description = ""
authors = ["buhovets <x10c@duck.com>"]
readme = "README.md"
packages = [{include = "roadmap_project"}]

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^7.2.2"
sphinx-rtd-theme = "^1.2.2"
fastapi = "^0.101.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
