"""empty message

Revision ID: 119f5fc4c082
Revises: dc1902110284
Create Date: 2023-09-01 17:40:18.607621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119f5fc4c082'
down_revision = 'dc1902110284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'roadmaps', 'categories', ['category_id'], ['id'])
    op.drop_column('roadmaps', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.drop_column('roadmaps', 'category_id')
    # ### end Alembic commands ###
