"""empty message

Revision ID: 9ef589c75e5f
Revises: 119f5fc4c082
Create Date: 2023-11-10 06:39:37.152523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef589c75e5f'
down_revision = '119f5fc4c082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
