"""empty message

Revision ID: dc1902110284
Revises: af6abb179ec8
Create Date: 2023-09-01 17:16:35.245963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1902110284'
down_revision = 'af6abb179ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roadmap_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('progress')
    op.drop_constraint('categories_roadmap_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'roadmap_id')
    op.add_column('posts', sa.Column('links', sa.JSON(), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.add_column('roadmaps', sa.Column('category', sa.String(), nullable=False))
    op.drop_constraint('roadmaps_user_id_fkey', 'roadmaps', type_='foreignkey')
    op.drop_column('roadmaps', 'user_id')
    op.add_column('steps', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('steps_parent_step_id_fkey', 'steps', type_='foreignkey')
    op.drop_column('steps', 'parent_step_id')
    op.drop_column('steps', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('steps', sa.Column('parent_step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('steps_parent_step_id_fkey', 'steps', 'steps', ['parent_step_id'], ['id'])
    op.drop_column('steps', 'description')
    op.add_column('roadmaps', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('roadmaps_user_id_fkey', 'roadmaps', 'users', ['user_id'], ['id'])
    op.drop_column('roadmaps', 'category')
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'links')
    op.add_column('categories', sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_roadmap_id_fkey', 'categories', 'roadmaps', ['roadmap_id'], ['id'])
    op.create_table('progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['steps.id'], name='progress_current_step_id_fkey'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name='progress_roadmap_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='progress_pkey')
    )
    op.drop_table('user_roadmap_association')
    # ### end Alembic commands ###
