import json
import os

from dotenv import load_dotenv

load_dotenv()

POSTGRES_NAME = os.getenv("POSTGRES_NAME")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

TEST_POSTGRES_NAME = os.getenv("TEST_POSTGRES_NAME")
TEST_POSTGRES_USER = os.getenv("TEST_POSTGRES_USER")
TEST_POSTGRES_PASSWORD = os.getenv("TEST_POSTGRES_PASSWORD")
TEST_POSTGRES_HOST = os.getenv("TEST_POSTGRES_HOST")
TEST_POSTGRES_PORT = os.getenv("TEST_POSTGRES_PORT")

DATABASE_URL = \
    f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_NAME}"

TEST_DATABASE_URL = \
    f"postgresql+asyncpg://{TEST_POSTGRES_USER}:{TEST_POSTGRES_PASSWORD}@{TEST_POSTGRES_HOST}:{TEST_POSTGRES_PORT}/{TEST_POSTGRES_NAME}"

JWT_SECRET = os.getenv("JWT_SECRET")
JWT_ACCESS_TTL = int(os.getenv("JWT_ACCESS_TTL"))
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")

CORS_ORIGINS = json.loads(os.getenv("CORS_ORIGINS"))
